services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_CLUSTER=${DB_CLUSTER}
      - DB_NAME=${DB_NAME}
      - MAX_PRODUCTS_EXTRACT=${MAX_PRODUCTS_EXTRACT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
